import { Category, Product } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'ceramics',
    name: 'Ceramics & Tableware',
    slug: 'ceramics-tableware',
    description: 'Hand-thrown stoneware, matte glazes, and tactile tabletop objects.',
    image_url: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?q=80&w=1200&auto=format&fit=crop',
  },
  {
    id: 'lighting',
    name: 'Architectural Lighting',
    slug: 'architectural-lighting',
    description: 'Sculptural ambient lamps, cast aluminum pendants, and warm diffuse luminaires.',
    image_url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=1200&auto=format&fit=crop',
  },
  {
    id: 'textiles',
    name: 'Organic Textiles',
    slug: 'organic-textiles',
    description: 'Stonewashed Belgian linen, hand-loomed wool throws, and ribbed waffle weaves.',
    image_url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=1200&auto=format&fit=crop',
  },
  {
    id: 'decor',
    name: 'Objects & Decor',
    slug: 'objects-decor',
    description: 'Solid walnut catchalls, fluted smoked glass carafes, and travertine bookends.',
    image_url: 'https://images.unsplash.com/photo-1534349762230-e0cadf78f5da?q=80&w=1200&auto=format&fit=crop',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    title: 'Kanso Stoneware Vase - Chalk White',
    slug: 'kanso-stoneware-vase-chalk-white',
    description: 'Individually wheel-thrown in Kyoto clay with an unglazed raw exterior and a waterproof silky interior glaze. Designed to elevate singular botanical stems or stand alone as a minimalist sculpture.',
    price: 68.0,
    compare_at_price: 85.0,
    category_id: 'ceramics',
    category_name: 'Ceramics & Tableware',
    image_url: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.9,
    rating_count: 38,
    stock: 15,
    featured: true,
    dimensions: 'H 24cm × Ø 14cm',
    materials: 'High-fire stoneware clay, mineral glaze',
  },
  {
    id: 'prod_2',
    title: 'Nara Matte Porcelain Mug (Set of 2)',
    slug: 'nara-matte-porcelain-mug-set',
    description: 'Ergonomically balanced coffee and tea vessels with an ultra-matte exterior and pleasant tactile heft. Dishwasher and microwave safe.',
    price: 42.0,
    compare_at_price: null,
    category_id: 'ceramics',
    category_name: 'Ceramics & Tableware',
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.8,
    rating_count: 54,
    stock: 22,
    featured: false,
    dimensions: '350ml capacity each',
    materials: 'Fine vitrified porcelain',
  },
  {
    id: 'prod_3',
    title: 'Travertine Column Table Lamp',
    slug: 'travertine-column-table-lamp',
    description: 'Carved from monolithic Italian travertine stone with an integrated warm 2700K dimmable LED ring. Casts a soft ambient halo suitable for credenzas, nightstands, and reading desks.',
    price: 195.0,
    compare_at_price: 240.0,
    category_id: 'lighting',
    category_name: 'Architectural Lighting',
    image_url: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 5.0,
    rating_count: 27,
    stock: 8,
    featured: true,
    dimensions: 'H 32cm × W 16cm × D 16cm',
    materials: 'Natural unfilled Roman travertine, brass brass rotary dimmer',
  },
  {
    id: 'prod_4',
    title: 'Halo Spun Brass Pendant Light',
    slug: 'halo-spun-brass-pendant-light',
    description: 'Spun solid brass shade with a brushed satin finish and white reflective interior. Includes a braided 2m textile cord and matching ceiling canopy.',
    price: 145.0,
    compare_at_price: null,
    category_id: 'lighting',
    category_name: 'Architectural Lighting',
    image_url: 'https://images.unsplash.com/photo-1540932239986-30128078f3c5?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1540932239986-30128078f3c5?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1517991104123-1d56a6e81ed9?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.7,
    rating_count: 19,
    stock: 12,
    featured: false,
    dimensions: 'Ø 38cm × H 18cm',
    materials: 'Hand-spun solid brass, linen braided cable',
  },
  {
    id: 'prod_5',
    title: 'Belgian Washed Linen Throw - Oat',
    slug: 'belgian-washed-linen-throw-oat',
    description: 'Pre-washed for extraordinary softness and breathable year-round comfort. Crafted from certified organic flax cultivated in Western Europe with frayed fringe detailing.',
    price: 120.0,
    compare_at_price: 150.0,
    category_id: 'textiles',
    category_name: 'Organic Textiles',
    image_url: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600121848594-d8644e57abab?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.9,
    rating_count: 42,
    stock: 18,
    featured: true,
    dimensions: '140cm × 200cm',
    materials: '100% GOTS certified organic flax linen (240 GSM)',
  },
  {
    id: 'prod_6',
    title: 'Nordic Ribbed Merino Wool Throw - Sand',
    slug: 'nordic-ribbed-merino-wool-throw-sand',
    description: 'Sumptuously dense 100% extrafine merino wool knitted in an architectural rib stitch. Hypoallergenic and naturally temperature-regulating.',
    price: 165.0,
    compare_at_price: null,
    category_id: 'textiles',
    category_name: 'Organic Textiles',
    image_url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.8,
    rating_count: 31,
    stock: 10,
    featured: false,
    dimensions: '130cm × 180cm',
    materials: '100% Extrafine Merino Wool',
  },
  {
    id: 'prod_7',
    title: 'Solid American Walnut Catchall Tray',
    slug: 'solid-american-walnut-catchall-tray',
    description: 'Precision milled from a single block of sustainably harvested black walnut, hand-finished with organic beeswax. Perfect for keys, timepieces, jewelry, and desk essentials.',
    price: 58.0,
    compare_at_price: 70.0,
    category_id: 'decor',
    category_name: 'Objects & Decor',
    image_url: 'https://images.unsplash.com/photo-1534349762230-e0cadf78f5da?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1534349762230-e0cadf78f5da?q=80&w=1000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.9,
    rating_count: 63,
    stock: 25,
    featured: true,
    dimensions: '28cm × 18cm × 2.5cm',
    materials: 'FSC-Certified American Black Walnut, Natural Beeswax Oil',
  },
  {
    id: 'prod_8',
    title: 'Smoked Fluted Glass Carafe & Tumbler',
    slug: 'smoked-fluted-glass-carafe-tumbler',
    description: 'Mouth-blown borosilicate glass featuring delicate vertical fluting. The matching tumbler nests neatly as a dust-free lid on bedside tables or dining surfaces.',
    price: 54.0,
    compare_at_price: null,
    category_id: 'decor',
    category_name: 'Objects & Decor',
    image_url: 'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?q=80&w=1000&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?q=80&w=1000&auto=format&fit=crop',
    ],
    rating: 4.6,
    rating_count: 22,
    stock: 14,
    featured: false,
    dimensions: 'Carafe 850ml, Tumbler 220ml',
    materials: 'Mouth-blown heat resistant borosilicate glass',
  },
];
